// src/data/mockData.js

export const brands = ['Apple', 'Samsung', 'Google', 'Huawei', 'OnePlus', 'Xiaomi', 'Dell', 'Lenovo', 'HP', 'Microsoft'];
export const storageOptions = ['32GB', '64GB', '128GB', '256GB', '512GB', '1TB'];

export const products = [
  // ========== TECHNOLOGY PRODUCTS (25) ==========
    {
    id: 1,
    name: 'iPhone 15 Pro',
    price: 999.99,
    rating: 9.2,
    orders: 420,
    image: 'https://picsum.photos/200/300?random=1',
    category: 'phones',
    brand: 'Apple',
    storage: '128GB',
    freeShipping: true
  },
  {
    id: 2,
    name: 'Samsung Galaxy S24',
    price: 849.99,
    rating: 8.8,
    orders: 380,
    image: 'https://picsum.photos/200/300?random=2',
    category: 'phones',
    brand: 'Samsung',
    storage: '256GB',
    freeShipping: true
  },
  {
    id: 3,
    name: 'Google Pixel 8 Pro',
    price: 799.99,
    rating: 8.5,
    orders: 290,
    image: 'https://picsum.photos/200/300?random=3',
    category: 'phones',
    brand: 'Google',
    storage: '128GB',
    freeShipping: true
  },
  {
    id: 4,
    name: 'MacBook Air M2',
    price: 1199.99,
    rating: 9.4,
    orders: 510,
    image: 'https://picsum.photos/200/300?random=4',
    category: 'laptops',
    brand: 'Apple',
    storage: '256GB',
    freeShipping: true
  },
  {
    id: 5,
    name: 'Dell XPS 13',
    price: 999.99,
    rating: 8.7,
    orders: 340,
    image: 'https://picsum.photos/200/300?random=5',
    category: 'laptops',
    brand: 'Dell',
    storage: '512GB',
    freeShipping: false
  },
  {
    id: 6,
    name: 'iPad Pro 12.9"',
    price: 1099.99,
    rating: 9.1,
    orders: 470,
    image: 'https://picsum.photos/200/300?random=6',
    category: 'ipads',
    brand: 'Apple',
    storage: '256GB',
    freeShipping: true
  },
  {
    id: 7,
    name: 'Samsung Galaxy Tab S9',
    price: 799.99,
    rating: 8.3,
    orders: 220,
    image: 'https://picsum.photos/200/300?random=7',
    category: 'tablets',
    brand: 'Samsung',
    storage: '128GB',
    freeShipping: true
  },
  {
    id: 8,
    name: 'iPhone 14',
    price: 699.99,
    rating: 8.0,
    orders: 180,
    image: 'https://picsum.photos/200/300?random=8',
    category: 'phones',
    brand: 'Apple',
    storage: '64GB',
    freeShipping: false
  },
  {
    id: 9,
    name: 'OnePlus 11',
    price: 699.99,
    rating: 8.6,
    orders: 310,
    image: 'https://picsum.photos/200/300?random=9',
    category: 'phones',
    brand: 'OnePlus',
    storage: '256GB',
    freeShipping: true
  },
  {
    id: 10,
    name: 'iPad Air',
    price: 599.99,
    rating: 8.4,
    orders: 390,
    image: 'https://picsum.photos/200/300?random=10',
    category: 'ipads',
    brand: 'Apple',
    storage: '64GB',
    freeShipping: true
  },
  {
    id: 11,
    name: 'Microsoft Surface Pro 9',
    price: 1299.99,
    rating: 8.9,
    orders: 270,
    image: 'https://picsum.photos/200/300?random=11',
    category: 'tablets',
    brand: 'Microsoft',
    storage: '256GB',
    freeShipping: true
  },
  {
    id: 12,
    name: 'iPod Touch',
    price: 199.99,
    rating: 7.2,
    orders: 85,
    image: 'https://picsum.photos/200/300?random=12',
    category: 'ipod',
    brand: 'Apple',
    storage: '32GB',
    freeShipping: false
  },
  {
    id: 13,
    name: 'Lenovo ThinkPad X1',
    price: 1499.99,
    rating: 9.0,
    orders: 190,
    image: 'https://picsum.photos/200/300?random=13',
    category: 'laptops',
    brand: 'Lenovo',
    storage: '1TB',
    freeShipping: true
  },
  {
    id: 14,
    name: 'Huawei MatePad Pro',
    price: 549.99,
    rating: 7.8,
    orders: 120,
    image: 'https://picsum.photos/200/300?random=14',
    category: 'tablets',
    brand: 'Huawei',
    storage: '128GB',
    freeShipping: true
  },
  {
    id: 15,
    name: 'iPhone SE',
    price: 429.99,
    rating: 7.5,
    orders: 210,
    image: 'https://picsum.photos/200/300?random=15',
    category: 'phones',
    brand: 'Apple',
    storage: '64GB',
    freeShipping: false
  },
  {
    id: 16,
    name: 'Samsung Galaxy Z Flip5',
    price: 999.99,
    rating: 8.7,
    orders: 150,
    image: 'https://picsum.photos/200/300?random=16',
    category: 'phones',
    brand: 'Samsung',
    storage: '256GB',
    freeShipping: true
  },
  {
    id: 17,
    name: 'iPad Mini',
    price: 499.99,
    rating: 8.2,
    orders: 330,
    image: 'https://picsum.photos/200/300?random=17',
    category: 'ipads',
    brand: 'Apple',
    storage: '64GB',
    freeShipping: true
  },
  {
    id: 18,
    name: 'MacBook Pro 16"',
    price: 2499.99,
    rating: 9.6,
    orders: 180,
    image: 'https://picsum.photos/200/300?random=18',
    category: 'laptops',
    brand: 'Apple',
    storage: '1TB',
    freeShipping: true
  },
  {
    id: 19,
    name: 'Google Pixel Tablet',
    price: 499.99,
    rating: 8.1,
    orders: 140,
    image: 'https://picsum.photos/200/300?random=19',
    category: 'tablets',
    brand: 'Google',
    storage: '128GB',
    freeShipping: true
  },
  {
    id: 20,
    name: 'iPod Nano',
    price: 149.99,
    rating: 6.8,
    orders: 45,
    image: 'https://picsum.photos/200/300?random=20',
    category: 'ipod',
    brand: 'Apple',
    storage: '16GB',
    freeShipping: false
  },
  {
    id: 21,
    name: 'Xiaomi Redmi Note 13',
    price: 299.99,
    rating: 7.9,
    orders: 420,
    image: 'https://picsum.photos/200/300?random=21',
    category: 'phones',
    brand: 'Xiaomi',
    storage: '128GB',
    freeShipping: true
  },
  {
    id: 22,
    name: 'HP Spectre x360',
    price: 1349.99,
    rating: 8.8,
    orders: 160,
    image: 'https://picsum.photos/200/300?random=22',
    category: 'laptops',
    brand: 'HP',
    storage: '512GB',
    freeShipping: true
  },
  {
    id: 23,
    name: 'Samsung Galaxy Tab A8',
    price: 229.99,
    rating: 7.4,
    orders: 280,
    image: 'https://picsum.photos/200/300?random=23',
    category: 'tablets',
    brand: 'Samsung',
    storage: '32GB',
    freeShipping: false
  },
  {
    id: 24,
    name: 'iPhone 13 Mini',
    price: 599.99,
    rating: 8.3,
    orders: 190,
    image: 'https://picsum.photos/200/300?random=24',
    category: 'phones',
    brand: 'Apple',
    storage: '128GB',
    freeShipping: true
  },
  {
    id: 25,
    name: 'Microsoft Surface Laptop 5',
    price: 1299.99,
    rating: 8.9,
    orders: 130,
    image: 'https://picsum.photos/200/300?random=25',
    category: 'laptops',
    brand: 'Microsoft',
    storage: '512GB',
    freeShipping: true
  },

  // ========== CLOTHING PRODUCTS (25) ==========
  {
    id: 26,
    name: 'Classic White T-Shirt',
    price: 19.99,
    rating: 8.5,
    orders: 890,
    image: 'https://picsum.photos/200/300?random=26',
    category: 'clothing',
    brand: 'BasicWear',
    size: 'M',
    freeShipping: true
  },
  {
    id: 27,
    name: 'Denim Jacket',
    price: 59.99,
    rating: 9.1,
    orders: 450,
    image: 'https://picsum.photos/200/300?random=27',
    category: 'clothing',
    brand: 'DenimCo',
    size: 'L',
    freeShipping: true
  },
  {
    id: 28,
    name: 'Cotton Hoodie',
    price: 39.99,
    rating: 8.8,
    orders: 670,
    image: 'https://picsum.photos/200/300?random=28',
    category: 'clothing',
    brand: 'ComfortWear',
    size: 'XL',
    freeShipping: true
  },
  {
    id: 29,
    name: 'Formal Dress Shirt',
    price: 45.99,
    rating: 8.3,
    orders: 320,
    image: 'https://picsum.photos/200/300?random=29',
    category: 'clothing',
    brand: 'ElegantStyle',
    size: 'M',
    freeShipping: false
  },
  {
    id: 30,
    name: 'Summer Shorts',
    price: 24.99,
    rating: 8.0,
    orders: 780,
    image: 'https://picsum.photos/200/300?random=30',
    category: 'clothing',
    brand: 'SummerBreeze',
    size: 'S',
    freeShipping: true
  },
  {
    id: 31,
    name: 'Wool Sweater',
    price: 79.99,
    rating: 9.2,
    orders: 290,
    image: 'https://picsum.photos/200/300?random=31',
    category: 'clothing',
    brand: 'WinterComfort',
    size: 'L',
    freeShipping: true
  },
  {
    id: 32,
    name: 'Yoga Pants',
    price: 34.99,
    rating: 8.7,
    orders: 920,
    image: 'https://picsum.photos/200/300?random=32',
    category: 'clothing',
    brand: 'ActiveFit',
    size: 'M',
    freeShipping: true
  },
  {
    id: 33,
    name: 'Leather Jacket',
    price: 199.99,
    rating: 9.4,
    orders: 180,
    image: 'https://picsum.photos/200/300?random=33',
    category: 'clothing',
    brand: 'PremiumLeather',
    size: 'XL',
    freeShipping: true
  },
  {
    id: 34,
    name: 'Casual Blazer',
    price: 89.99,
    rating: 8.6,
    orders: 340,
    image: 'https://picsum.photos/200/300?random=34',
    category: 'clothing',
    brand: 'UrbanStyle',
    size: 'M',
    freeShipping: true
  },
  {
    id: 35,
    name: 'Striped Polo Shirt',
    price: 32.99,
    rating: 8.2,
    orders: 560,
    image: 'https://picsum.photos/200/300?random=35',
    category: 'clothing',
    brand: 'ClassicPolo',
    size: 'L',
    freeShipping: true
  },
  {
    id: 36,
    name: 'Knit Cardigan',
    price: 54.99,
    rating: 8.9,
    orders: 410,
    image: 'https://picsum.photos/200/300?random=36',
    category: 'clothing',
    brand: 'CozyWear',
    size: 'S',
    freeShipping: true
  },
  {
    id: 37,
    name: 'Cargo Pants',
    price: 42.99,
    rating: 8.4,
    orders: 380,
    image: 'https://picsum.photos/200/300?random=37',
    category: 'clothing',
    brand: 'UtilityWear',
    size: 'M',
    freeShipping: false
  },
  {
    id: 38,
    name: 'Silk Scarf',
    price: 29.99,
    rating: 8.7,
    orders: 230,
    image: 'https://picsum.photos/200/300?random=38',
    category: 'clothing',
    brand: 'LuxurySilk',
    size: 'One Size',
    freeShipping: true
  },
  {
    id: 39,
    name: 'Winter Parka',
    price: 149.99,
    rating: 9.3,
    orders: 190,
    image: 'https://picsum.photos/200/300?random=39',
    category: 'clothing',
    brand: 'ArcticWarm',
    size: 'XL',
    freeShipping: true
  },
  {
    id: 40,
    name: 'Linen Shirt',
    price: 47.99,
    rating: 8.5,
    orders: 270,
    image: 'https://picsum.photos/200/300?random=40',
    category: 'clothing',
    brand: 'Breathable',
    size: 'M',
    freeShipping: true
  },
  {
    id: 41,
    name: 'Graphic Tee',
    price: 22.99,
    rating: 8.1,
    orders: 680,
    image: 'https://picsum.photos/200/300?random=41',
    category: 'clothing',
    brand: 'UrbanArt',
    size: 'L',
    freeShipping: true
  },
  {
    id: 42,
    name: 'Evening Gown',
    price: 129.99,
    rating: 9.0,
    orders: 95,
    image: 'https://picsum.photos/200/300?random=42',
    category: 'clothing',
    brand: 'ElegantNight',
    size: 'S',
    freeShipping: true
  },
  {
    id: 43,
    name: 'Sports Jacket',
    price: 67.99,
    rating: 8.6,
    orders: 320,
    image: 'https://picsum.photos/200/300?random=43',
    category: 'clothing',
    brand: 'ActiveWear',
    size: 'M',
    freeShipping: true
  },
  {
    id: 44,
    name: 'Chino Pants',
    price: 39.99,
    rating: 8.3,
    orders: 540,
    image: 'https://picsum.photos/200/300?random=44',
    category: 'clothing',
    brand: 'CasualStyle',
    size: 'L',
    freeShipping: true
  },
  {
    id: 45,
    name: 'Turtleneck Sweater',
    price: 49.99,
    rating: 8.7,
    orders: 290,
    image: 'https://picsum.photos/200/300?random=45',
    category: 'clothing',
    brand: 'WinterStyle',
    size: 'M',
    freeShipping: true
  },
  {
    id: 46,
    name: 'Bomber Jacket',
    price: 74.99,
    rating: 8.9,
    orders: 210,
    image: 'https://picsum.photos/200/300?random=46',
    category: 'clothing',
    brand: 'UrbanFlight',
    size: 'L',
    freeShipping: true
  },
  {
    id: 47,
    name: 'Maxi Dress',
    price: 59.99,
    rating: 8.8,
    orders: 180,
    image: 'https://picsum.photos/200/300?random=47',
    category: 'clothing',
    brand: 'SummerFlow',
    size: 'S',
    freeShipping: true
  },
  {
    id: 48,
    name: 'Puffer Vest',
    price: 64.99,
    rating: 8.4,
    orders: 160,
    image: 'https://picsum.photos/200/300?random=48',
    category: 'clothing',
    brand: 'OutdoorComfort',
    size: 'M',
    freeShipping: false
  },
  {
    id: 49,
    name: 'Business Suit',
    price: 299.99,
    rating: 9.5,
    orders: 120,
    image: 'https://picsum.photos/200/300?random=49',
    category: 'clothing',
    brand: 'ExecutiveWear',
    size: 'L',
    freeShipping: true
  },
  {
    id: 50,
    name: 'Beach Cover-up',
    price: 27.99,
    rating: 7.9,
    orders: 340,
    image: 'https://picsum.photos/200/300?random=50',
    category: 'clothing',
    brand: 'SummerVibes',
    size: 'M',
    freeShipping: true
  },

  // ========== FURNITURE PRODUCTS (25) ==========
  {
    id: 51,
    name: 'Modern Sofa',
    price: 899.99,
    rating: 9.2,
    orders: 85,
    image: 'https://picsum.photos/200/300?random=51',
    category: 'furniture',
    brand: 'ComfortLiving',
    material: 'Fabric',
    freeShipping: false
  },
  {
    id: 52,
    name: 'Wooden Dining Table',
    price: 459.99,
    rating: 9.0,
    orders: 67,
    image: 'https://picsum.photos/200/300?random=52',
    category: 'furniture',
    brand: 'NaturalWood',
    material: 'Oak',
    freeShipping: false
  },
  {
    id: 53,
    name: 'Office Chair',
    price: 199.99,
    rating: 8.7,
    orders: 210,
    image: 'https://picsum.photos/200/300?random=53',
    category: 'furniture',
    brand: 'ErgoComfort',
    material: 'Mesh',
    freeShipping: true
  },
  {
    id: 54,
    name: 'King Size Bed',
    price: 1299.99,
    rating: 9.4,
    orders: 45,
    image: 'https://picsum.photos/200/300?random=54',
    category: 'furniture',
    brand: 'SleepWell',
    material: 'Wood',
    freeShipping: false
  },
  {
    id: 55,
    name: 'Bookshelf',
    price: 179.99,
    rating: 8.5,
    orders: 120,
    image: 'https://picsum.photos/200/300?random=55',
    category: 'furniture',
    brand: 'StorageMaster',
    material: 'Particle Board',
    freeShipping: true
  },
  {
    id: 56,
    name: 'Coffee Table',
    price: 229.99,
    rating: 8.8,
    orders: 89,
    image: 'https://picsum.photos/200/300?random=56',
    category: 'furniture',
    brand: 'ModernHome',
    material: 'Glass',
    freeShipping: false
  },
  {
    id: 57,
    name: 'Recliner Chair',
    price: 399.99,
    rating: 9.1,
    orders: 78,
    image: 'https://picsum.photos/200/300?random=57',
    category: 'furniture',
    brand: 'RelaxMax',
    material: 'Leather',
    freeShipping: false
  },
  {
    id: 58,
    name: 'Wardrobe Cabinet',
    price: 599.99,
    rating: 8.9,
    orders: 56,
    image: 'https://picsum.photos/200/300?random=58',
    category: 'furniture',
    brand: 'ClosetSpace',
    material: 'Wood',
    freeShipping: false
  },
  {
    id: 59,
    name: 'Bar Stool',
    price: 89.99,
    rating: 8.3,
    orders: 145,
    image: 'https://picsum.photos/200/300?random=59',
    category: 'furniture',
    brand: 'KitchenEssentials',
    material: 'Metal',
    freeShipping: true
  },
  {
    id: 60,
    name: 'TV Stand',
    price: 279.99,
    rating: 8.6,
    orders: 98,
    image: 'https://picsum.photos/200/300?random=60',
    category: 'furniture',
    brand: 'EntertainmentCenter',
    material: 'Wood',
    freeShipping: false
  },
  {
    id: 61,
    name: 'Accent Chair',
    price: 159.99,
    rating: 8.4,
    orders: 110,
    image: 'https://picsum.photos/200/300?random=61',
    category: 'furniture',
    brand: 'StyleHome',
    material: 'Velvet',
    freeShipping: true
  },
  {
    id: 62,
    name: 'Dresser',
    price: 429.99,
    rating: 8.7,
    orders: 67,
    image: 'https://picsum.photos/200/300?random=62',
    category: 'furniture',
    brand: 'BedroomEssentials',
    material: 'Wood',
    freeShipping: false
  },
  {
    id: 63,
    name: 'Patio Set',
    price: 799.99,
    rating: 9.0,
    orders: 34,
    image: 'https://picsum.photos/200/300?random=63',
    category: 'furniture',
    brand: 'OutdoorLiving',
    material: 'Rattan',
    freeShipping: false
  },
  {
    id: 64,
    name: 'Desk Lamp',
    price: 49.99,
    rating: 8.2,
    orders: 230,
    image: 'https://picsum.photos/200/300?random=64',
    category: 'furniture',
    brand: 'BrightLight',
    material: 'Metal',
    freeShipping: true
  },
  {
    id: 65,
    name: 'Shoe Rack',
    price: 69.99,
    rating: 8.1,
    orders: 180,
    image: 'https://picsum.photos/200/300?random=65',
    category: 'furniture',
    brand: 'OrganizeIt',
    material: 'Plastic',
    freeShipping: true
  },
  {
    id: 66,
    name: 'Bookshelf Ladder',
    price: 329.99,
    rating: 8.8,
    orders: 42,
    image: 'https://picsum.photos/200/300?random=66',
    category: 'furniture',
    brand: 'RusticStyle',
    material: 'Wood',
    freeShipping: false
  },
  {
    id: 67,
    name: 'Console Table',
    price: 189.99,
    rating: 8.5,
    orders: 75,
    image: 'https://picsum.photos/200/300?random=67',
    category: 'furniture',
    brand: 'EntrywayDesign',
    material: 'Wood',
    freeShipping: true
  },
  {
    id: 68,
    name: 'Bean Bag Chair',
    price: 79.99,
    rating: 7.9,
    orders: 160,
    image: 'https://picsum.photos/200/300?random=68',
    category: 'furniture',
    brand: 'ComfortZone',
    material: 'Faux Leather',
    freeShipping: true
  },
  {
    id: 69,
    name: 'Nightstand',
    price: 129.99,
    rating: 8.6,
    orders: 95,
    image: 'https://picsum.photos/200/300?random=69',
    category: 'furniture',
    brand: 'BedroomComfort',
    material: 'Wood',
    freeShipping: true
  },
  {
    id: 70,
    name: 'Folding Chair Set',
    price: 149.99,
    rating: 8.0,
    orders: 120,
    image: 'https://picsum.photos/200/300?random=70',
    category: 'furniture',
    brand: 'EventEssentials',
    material: 'Plastic',
    freeShipping: true
  },
  {
    id: 71,
    name: 'Rocking Chair',
    price: 249.99,
    rating: 8.9,
    orders: 58,
    image: 'https://picsum.photos/200/300?random=71',
    category: 'furniture',
    brand: 'VintageStyle',
    material: 'Wood',
    freeShipping: false
  },
  {
    id: 72,
    name: 'Storage Ottoman',
    price: 119.99,
    rating: 8.4,
    orders: 85,
    image: 'https://picsum.photos/200/300?random=72',
    category: 'furniture',
    brand: 'MultiUse',
    material: 'Fabric',
    freeShipping: true
  },
  {
    id: 73,
    name: 'Bookshelf Wall Unit',
    price: 699.99,
    rating: 9.3,
    orders: 29,
    image: 'https://picsum.photos/200/300?random=73',
    category: 'furniture',
    brand: 'WallDesign',
    material: 'Wood',
    freeShipping: false
  },
  {
    id: 74,
    name: 'Bar Cabinet',
    price: 449.99,
    rating: 8.7,
    orders: 38,
    image: 'https://picsum.photos/200/300?random=74',
    category: 'furniture',
    brand: 'EntertainmentBar',
    material: 'Wood',
    freeShipping: false
  },
  {
    id: 75,
    name: 'Floor Mirror',
    price: 159.99,
    rating: 8.5,
    orders: 67,
    image: 'https://picsum.photos/200/300?random=75',
    category: 'furniture',
    brand: 'ReflectStyle',
    material: 'Glass',
    freeShipping: false
  },

  // ========== TOYS PRODUCTS (15) ==========
  {
    id: 76,
    name: 'Building Blocks Set',
    price: 29.99,
    rating: 8.8,
    orders: 340,
    image: 'https://picsum.photos/200/300?random=76',
    category: 'toys',
    brand: 'CreativeKids',
    ageRange: '3-8 years',
    freeShipping: true
  },
  {
    id: 77,
    name: 'Remote Control Car',
    price: 49.99,
    rating: 8.5,
    orders: 280,
    image: 'https://picsum.photos/200/300?random=77',
    category: 'toys',
    brand: 'TechToys',
    ageRange: '6-12 years',
    freeShipping: true
  },
  {
    id: 78,
    name: 'Educational Tablet',
    price: 39.99,
    rating: 8.7,
    orders: 190,
    image: 'https://picsum.photos/200/300?random=78',
    category: 'toys',
    brand: 'LearnFun',
    ageRange: '3-7 years',
    freeShipping: true
  },
  {
    id: 79,
    name: 'Doll House',
    price: 79.99,
    rating: 9.0,
    orders: 120,
    image: 'https://picsum.photos/200/300?random=79',
    category: 'toys',
    brand: 'DreamHouse',
    ageRange: '4-10 years',
    freeShipping: false
  },
  {
    id: 80,
    name: 'Puzzle Set',
    price: 19.99,
    rating: 8.3,
    orders: 450,
    image: 'https://picsum.photos/200/300?random=80',
    category: 'toys',
    brand: 'BrainGames',
    ageRange: '5+ years',
    freeShipping: true
  },
  {
    id: 81,
    name: 'Action Figure Set',
    price: 34.99,
    rating: 8.6,
    orders: 210,
    image: 'https://picsum.photos/200/300?random=81',
    category: 'toys',
    brand: 'HeroWorld',
    ageRange: '4-12 years',
    freeShipping: true
  },
  {
    id: 82,
    name: 'Art Supplies Kit',
    price: 24.99,
    rating: 8.9,
    orders: 320,
    image: 'https://picsum.photos/200/300?random=82',
    category: 'toys',
    brand: 'CreativeArts',
    ageRange: '3+ years',
    freeShipping: true
  },
  {
    id: 83,
    name: 'Science Experiment Kit',
    price: 44.99,
    rating: 9.1,
    orders: 150,
    image: 'https://picsum.photos/200/300?random=83',
    category: 'toys',
    brand: 'YoungScientist',
    ageRange: '8-14 years',
    freeShipping: true
  },
  {
    id: 84,
    name: 'Musical Instrument Set',
    price: 29.99,
    rating: 8.4,
    orders: 180,
    image: 'https://picsum.photos/200/300?random=84',
    category: 'toys',
    brand: 'MusicFun',
    ageRange: '2-6 years',
    freeShipping: true
  },
  {
    id: 85,
    name: 'Building Robot Kit',
    price: 69.99,
    rating: 9.2,
    orders: 95,
    image: 'https://picsum.photos/200/300?random=85',
    category: 'toys',
    brand: 'TechBuild',
    ageRange: '10-16 years',
    freeShipping: true
  },
  {
    id: 86,
    name: 'Plush Toy Set',
    price: 22.99,
    rating: 8.7,
    orders: 270,
    image: 'https://picsum.photos/200/300?random=86',
    category: 'toys',
    brand: 'CuddleFriends',
    ageRange: '0-5 years',
    freeShipping: true
  },
  {
    id: 87,
    name: 'Board Game Collection',
    price: 39.99,
    rating: 8.8,
    orders: 160,
    image: 'https://picsum.photos/200/300?random=87',
    category: 'toys',
    brand: 'FamilyGames',
    ageRange: '6+ years',
    freeShipping: true
  },
  {
    id: 88,
    name: 'Water Play Set',
    price: 34.99,
    rating: 8.5,
    orders: 140,
    image: 'https://picsum.photos/200/300?random=88',
    category: 'toys',
    brand: 'SummerFun',
    ageRange: '2-6 years',
    freeShipping: false
  },
  {
    id: 89,
    name: 'Magnetic Tiles',
    price: 54.99,
    rating: 9.3,
    orders: 110,
    image: 'https://picsum.photos/200/300?random=89',
    category: 'toys',
    brand: 'MagneticFun',
    ageRange: '3-10 years',
    freeShipping: true
  },
  {
    id: 90,
    name: 'Play Kitchen Set',
    price: 89.99,
    rating: 8.9,
    orders: 85,
    image: 'https://picsum.photos/200/300?random=90',
    category: 'toys',
    brand: 'ImaginationPlay',
    ageRange: '3-8 years',
    freeShipping: false
  },

  // ========== FOOTWEAR PRODUCTS (10) ==========
  {
    id: 91,
    name: 'Running Shoes',
    price: 89.99,
    rating: 8.9,
    orders: 420,
    image: 'https://picsum.photos/200/300?random=91',
    category: 'footwear',
    brand: 'RunFast',
    size: '9',
    freeShipping: true
  },
  {
    id: 92,
    name: 'Leather Sandals',
    price: 45.99,
    rating: 8.4,
    orders: 290,
    image: 'https://picsum.photos/200/300?random=92',
    category: 'footwear',
    brand: 'SummerWalk',
    size: '8',
    freeShipping: true
  },
  {
    id: 93,
    name: 'Formal Dress Shoes',
    price: 129.99,
    rating: 9.1,
    orders: 180,
    image: 'https://picsum.photos/200/300?random=93',
    category: 'footwear',
    brand: 'ElegantStep',
    size: '10',
    freeShipping: true
  },
  {
    id: 94,
    name: 'Casual Sneakers',
    price: 59.99,
    rating: 8.7,
    orders: 560,
    image: 'https://picsum.photos/200/300?random=94',
    category: 'footwear',
    brand: 'UrbanWalk',
    size: '9',
    freeShipping: true
  },
  {
    id: 95,
    name: 'Hiking Boots',
    price: 149.99,
    rating: 9.3,
    orders: 130,
    image: 'https://picsum.photos/200/300?random=95',
    category: 'footwear',
    brand: 'TrailMaster',
    size: '11',
    freeShipping: true
  },
  {
    id: 96,
    name: 'Flip Flops',
    price: 14.99,
    rating: 7.8,
    orders: 780,
    image: 'https://picsum.photos/200/300?random=96',
    category: 'footwear',
    brand: 'BeachDays',
    size: '8',
    freeShipping: true
  },
  {
    id: 97,
    name: 'Basketball Shoes',
    price: 119.99,
    rating: 8.8,
    orders: 210,
    image: 'https://picsum.photos/200/300?random=97',
    category: 'footwear',
    brand: 'CourtKing',
    size: '10',
    freeShipping: true
  },
  {
    id: 98,
    name: 'Comfort Slippers',
    price: 24.99,
    rating: 8.2,
    orders: 450,
    image: 'https://picsum.photos/200/300?random=98',
    category: 'footwear',
    brand: 'HomeComfort',
    size: '9',
    freeShipping: true
  },
  {
    id: 99,
    name: 'Designer Heels',
    price: 179.99,
    rating: 8.6,
    orders: 95,
    image: 'https://picsum.photos/200/300?random=99',
    category: 'footwear',
    brand: 'FashionStep',
    size: '7',
    freeShipping: true
  },
  {
    id: 100,
    name: 'Winter Boots',
    price: 99.99,
    rating: 8.9,
    orders: 160,
    image: 'https://picsum.photos/200/300?random=100',
    category: 'footwear',
    brand: 'SnowProof',
    size: '8',
    freeShipping: true
  }
];

export const categories = [
  'All',
  'Tablets',
  'Phones',
  'Ipads',
  'ipod',
  'Laptops',
  'Clothing',
  'Furniture',
  'Toys',
  'Footwear'
];

// Add this to your mockData.js file (replace the existing recommendedProducts)

export const recommendedProducts = [
  {
    id: 101,
    name: 'Wireless Earbuds Pro',
    price: 129.99,
    image: 'https://picsum.photos/200/300?random=101'
  },
  {
    id: 102,
    name: 'Smart Watch Series 8',
    price: 249.99,
    image: 'https://picsum.photos/200/300?random=102'
  },
  {
    id: 103,
    name: 'Bluetooth Speaker',
    price: 79.99,
    image: 'https://picsum.photos/200/300?random=103'
  },
  {
    id: 104,
    name: 'Phone Case - Premium',
    price: 24.99,
    image: 'https://picsum.photos/200/300?random=104'
  },
  {
    id: 105,
    name: 'USB-C Fast Charger',
    price: 34.99,
    image: 'https://picsum.photos/200/300?random=105'
  },
  {
    id: 106,
    name: 'Screen Protector Kit',
    price: 14.99,
    image: 'https://picsum.photos/200/300?random=106'
  },
  {
    id: 107,
    name: 'Laptop Backpack',
    price: 59.99,
    image: 'https://picsum.photos/200/300?random=107'
  },
  {
    id: 108,
    name: 'Wireless Mouse',
    price: 29.99,
    image: 'https://picsum.photos/200/300?random=108'
  }
];

// Helper functions - MUST be after products array
export const getProductsByCategory = (category) => {
  return products.filter(p => p.category === category.toLowerCase());
};

export const getProductById = (id) => {
  return products.find(p => p.id === id);
};